### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Tokiwa-17** [Tokiwa-17/Android#43]
- [x] 通过邮箱注册帐号，设置密码 2%
- [x] 修改用户名，头像，简介，密码 4%
- [x] 对用户进行关注和取关，显示关注列表，在动态页面的用户名后边显示“已关注” 3%
- [x] 对用户进行屏蔽，并不显示其动态 2%

##### 二级菜单：

- [x] 个人主页显示本人发布的所有动态 2%
- [x] 从作品、评论等界⾯进⼊他⼈的个人主⻚ 2%
- [x] 草稿页面保存未发布的作品草稿 2%
- [ ] 进⼊⼀篇草稿的编辑界⾯继续进行编辑或者删除 3%

#### 发布 16%

- [ ] 发布纯文字动态 1%
- [ ] 发布图文混合（包括调用相机进行拍照）2%
- [ ] 发布音频动态（包括调用麦克风进行录音）3%
- [ ] 发布视频动态（包括调用相机进行录像）3%
- [ ] 发布动态时添加位置信息（调用手机定位） 3%
- [ ] 编辑过程中⾃动保存草稿，发布完成后自动从草稿箱删除 4%

#### 查看 13%

- [x] 选择根据时间顺序或者点赞数量进行动态展示 3%
- [x] 选择根据所有人或者已关注的人进行动态展示 2%
- [x] 对动态进行点赞（展示所有的点赞人信息）2%
- [ ] 对动态进行评论（展示所有的回复信息）2%
- [ ] 对动态进行分享（分享到任何其他可展示内容的APP中）2%
- [x] 可以取消点赞，删除评论 2%

#### 通知 6%

- [ ] 接收到来⾃平台的通知消息，包括⾃⼰作品的点赞与评论，以及关注作者的更新 4%

- [x] ⽤⼾从个⼈中⼼界⾯进⼊通知消息列表 2%

#### 搜索 7%

- [x] 根据动态名称，动态内容，用户名称，作品类型（文图音视，在动态发布时选择）四种方式搜索内容 4%

- [x] 搜索时实现模糊搜索 3%

#### 系统支持 3%

- [ ] APP 应该被正确地签名打包，在指定版本的 Android 虚拟机及 Android智能手机上可以正常运行，不出现崩溃情况或 UI 样式错乱情况。
